### ISSUE TITLE
Crash when pushing back button after chatting

### ISSUE THREAD

**Issue by ThamTran9x** [tientham/BluetoothDemo#17]
After chatting with a paird device, I press back button (in the app or on my phone screen) to return the initial screen of the app, it is crashed and exit the app automatically

**Comment by tientham** [comment]
This issue has been fixed in:
 commit 4724a99a0220db498440eb5b24762cad4355e478 (HEAD -> tientham_devel_sw_main, origin/tientham_devel_sw_main)
