### ISSUE TITLE
Bug with Enter button on screen of Tab 2

### ISSUE THREAD

**Issue by ThamTran9x** [tientham/BluetoothDemo#21]
When user want to enter to cut the line, the app in Tab 2 defines Enter button as transferring the message rather than clicking Send icon on the screen of the app. It is not convenient for the users. This issue does not occur on Sony phone

**Comment by tientham** [comment]
This issue has been fixed in 
commit 4724a99a0220db498440eb5b24762cad4355e478 (HEAD -> tientham_devel_sw_main, origin/tientham_devel_sw_main)
