### ISSUE TITLE
Report: the icon of connection turns into black  

### ISSUE THREAD

**Issue by ThamTran9x** [tientham/BluetoothDemo#24]
When users change to use other things on their phone while this app still opens, and then they come back to this app. At this time the icon of connected turns into black rather than green as before

**Comment by tientham** [comment]
This issue has been fixed in:
commit 5d9222a1155cbd0f4e95ef5150882975ccbb9792 (HEAD -> tientham_devel_sw_main, origin/tientham_devel_sw_main)

**Comment by tientham** [comment]
Reference:
https://stackoverflow.com/questions/11504860/what-is-the-difference-between-the-states-selected-checked-and-activated-in-and
